project:
  type: website
  output-dir: docs

website:
  title: "Miray's Analytics Lab"
  navbar:
    title: "Miray's Analytics Lab"
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU660 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/sevvalmiray
      - icon: linkedin
        href: https://www.linkedin.com/in/sevvalmiray/

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU660 - Spring 2026" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme:
      light: [default, styles.scss]
      dark: [darkly, styles.scss]
    include-before-body: assets/progress-bar.html
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,wght@0,300;0,400;0,600;1,300&family=Playfair+Display:wght@500;600;700&display=swap" rel="stylesheet">


editor: visual

